version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: FggX@CfFf_zl
      MYSQL_DATABASE: sinsems_development
      MYSQL_USER: sinsems
      MYSQL_PASSWORD: sinsems123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  web:
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DB_HOST: db
      DB_USERNAME: root
      DB_PASSWORD: FggX@CfFf_zl
      DB_DATABASE: sinsems_development
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:create db:migrate && bundle exec rails server -b 0.0.0.0"

volumes:
  mysql_data:
  bundle_cache: 